name: Example Go CI Demo

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  demo:
    uses: ./.github/workflows/analyze.yml
    secrets: inherit
    with:
      command: go test -json -race -cover -timeout 10s ./...
      flags: nopreserveexitcode
      working-directory: examples/go-ci-demo
      go-version: "1.24.13"
